### PR TITLE
master-qa-51259

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-51259

### CODE REVIEW

**Comment by suilin** [comment]
ci:test

**Comment by suilin** [comment]
ci:test

**Comment by suilin** [comment]
ci:test

**Comment by suilin** [comment]
ci:test

**Comment by suilin** [comment]
ci:test

**Comment by suilin** [comment]
ci:test

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by vicnate5** [comment]
@suilin @xbrianlee Can you revert https://github.com/liferay/liferay-portal/commit/6d52e8db21e99395f6492b9bc5d92d03e9446521 when sending this in?

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by xbrianlee** [comment]
ci:test:norebase

**Comment by vicnate5** [comment]
Do we need the success message check here? https://testray.liferay.com/reports/production/logs/test-1-21/1565379205145/test-portal-acceptance-pullrequest(master)/4511/functional-tomcat90-mysql57-jdk8/2/0/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive704/index.html.gz

**Comment by xbrianlee** [comment]
Probably not, looks like that button is flaky

**Pull request closed without merging**
