### PR TITLE
LPS-177140 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-177140

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:publications:nocompile

**Comment by brookedalton** [comment]
ci:test:publications:nocompile

**Comment by suilin** [comment]
Hi @brookedalton, thanks for working on the automation test, there is a conflict issue, can you remove the second commit and resend it? Thanks!

**Comment by brookedalton** [comment]
Hi @suilin, sorry I thought I removed the second commit but I just removed it and rebased against master!

**Comment by suilin** [comment]
@brookedalton, thanks for working on it, and I also added steps to assert the change of the custom master page template under "Asset" category, for details you can see https://github.com/brianchandotcom/liferay-portal/pull/133688.

**Pull request closed without merging**
