### PR TITLE
LPS-146573

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LPS-146573
https://issues.liferay.com/browse/LRQA-75228
https://issues.liferay.com/browse/LRQA-75231
https://issues.liferay.com/browse/LRQA-75238

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:publications

**Comment by david-truong** [comment]
Can you send this to liferay-publications and then forward

**Comment by suilin** [comment]
Has been sent: https://github.com/liferay-publications/liferay-portal/pull/124.

**Pull request closed without merging**
