### PR TITLE
LRQA-52698 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-52698

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by xbrianlee** [comment]
ci:test

Let's see what happens for non-search suites 🤔

**Comment by suilin** [comment]
@xbrianlee Thank you for your reviewing.
1. Sorry, I didn't consider other components testing, this works on non-search tests.
2. We should add <not><isset property="remote.elasticsearch.enabled" /></not> since only embedded ES7 port is 9201
3. Without suite.search.engine will affect ci:test:search-es7 suite: those tests in search.testcase with embedded ES7 to curl command(with 9200), as my previous comment on the ticket.
So I change it again and resend to you on https://github.com/xbrianlee/liferay-portal/pull/382.

**Pull request closed without merging**
