### PR TITLE
master-qa-73427

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-73427
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by suilin** [comment]
Hi @jaydawu, thank you for working on it, I just change some minor changes:

1. I removed the property `property portal.acceptance = "true";` since we don't intend to add this case to acceptance suite now.
2. I removed some unusful steps.

**Comment by suilin** [comment]
continue in https://github.com/suilin/liferay-portal/pull/491

**Pull request closed without merging**
