### PR TITLE
master-qa-47900

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-47900

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:security

**Comment by suilin** [comment]
@xbrianlee, Following are the details of my changes
*  Only update the CAS and NTLM related test, since [LPS-90255](https://issues.liferay.com/browse/LPS-90255) only changed on them, and another reason is others authentication still works on portal setting and don't transfer to SSO completely, such as opensso(Test OpenSSO Configuration, Reset Values).
*  For the last commit 
	* I didn't change to FormFields.enableCheckbox since the locator is not unique.
	* Use FormFields.editText macro to instead of type function, has been verified on CAS and other authentication(on portal setting)
* AA the poshi result:
	* [LocalFile.Login#FacebookSSOSmoke](https://testray.liferay.com/home/-/testray/case_results/514476395?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D514468910%26testrayRunId%3D514468911%26cur%3D1%26delta%3D200%26orderByCol%3DtestrayComponentName_sortable%26orderByType%3Dasc) On this the appSecret, @type='password', not "text" so can't use FormFields.editText macro. I will forch to resend.
	* [LocalFile.Login#OpenIDConnectSmoke](https://testray.liferay.com/home/-/testray/case_results/514470782?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D514468910%26testrayRunId%3D514468911%26cur%3D1%26delta%3D200%26orderByCol%3DtestrayComponentName_sortable%26orderByType%3Dasc) not related to this
	* [LocalFile.Login#GoogleSSOSmoke](https://testray.liferay.com/home/-/testray/case_results/514470762?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D514468910%26testrayRunId%3D514468911%26cur%3D1%26delta%3D200%26orderByCol%3DtestrayComponentName_sortable%26orderByType%3Dasc) fluke, can't be reproduced on local.
* I'm not sure if you'd like change all of the authentication through SSO, so I didn't pull the PR to you.

Thank you!

**Comment by suilin** [comment]
[LocalFile.Login#FacebookSSOSmoke](https://testray.liferay.com/home/-/testray/case_results/514476395?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D514468910%26testrayRunId%3D514468911%26cur%3D1%26delta%3D200%26orderByCol%3DtestrayComponentName_sortable%26orderByType%3Dasc) On this the appSecret, @type='password', not "text" so can't use FormFields.editText macro.
[LocalFile.Login#OpenIDConnectSmoke], (https://testray.liferay.com/home/-/testray/case_results/514470782?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D514468910%26testrayRunId%3D514468911%26cur%3D1%26delta%3D200%26orderByCol%3DtestrayComponentName_sortable%26orderByType%3Dasc) not related to this
[LocalFile.Login#GoogleSSOSmoke](https://testray.liferay.com/home/-/testray/case_results/514470762?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D514468910%26testrayRunId%3D514468911%26cur%3D1%26delta%3D200%26orderByCol%3DtestrayComponentName_sortable%26orderByType%3Dasc) fluke, can't be reproduced on local.

**Comment by xbrianlee** [comment]
ci:test:security

**Pull request closed without merging**
