### PR TITLE
master-qa-175344

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LPS-175344

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:publications-as

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by joshchong** [comment]
Hey @suilin, I found the issue. there is a missing `)` in all of the places where `test.class.method.name != PublicationsWebContent#PublishWebContentWithCategory` is set in `publications-db`. Resolving this should get the suite to run on CI.

Also some minor things:
- Can you move all instances of `(testray.main.component.name == "Publications")` before the quarantine statements?
For example: 
```
        (\
            (database.types == null) OR \
            (database.types ~ oracle)\
        ) AND \
        (testray.main.component.name == "Publications") AND \
        (test.class.method.name != PublicationsWebContent#PublishWebContentWithCategory)
```

- Can you reword the suite descriptions at the top to: `# Publications with Different Application Server Environments` and `# Publications with Different Database Environments`

Thanks!

**Comment by suilin** [comment]
Hi @joshchong, thanks for helping me to figure out the issue, I will update it with the suggestions you provide. Thank you!

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
