### PR TITLE
LPS-173128

### PR DESCRIPTION
**Pull request by danielCamara02**
https://issues.liferay.com/browse/LPS-173128

### CODE REVIEW

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @danielCamara02, thanks for working on the ticket, could you look at the folllowing issues and resend it? Thanks!

1. The first two commits have been merged to upstream, could you rebase it? 
2. Due to new Poshi released, ""  are being deleted around @priority, could you update it?
3. Furthemore, We'd better not to use SF to make another changes for your previous change, you should update it through your first commit. 

cc @xbrianlee

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @danielCamara02, I made a small changes to make sure it's stable and complete.
1. Add step to navigate to wiki node before editing wiki page.
2. Add steps to review the wiki node and wiki page changes, publish publication as description mentioned.

**Pull request closed without merging**
