### PR TITLE
LPS-177148

### PR DESCRIPTION
**Pull request by prokofitch**
https://issues.liferay.com/browse/LPS-177148

Original pull request: https://github.com/CaiocSiqueira/liferay-portal/pull/30

### CODE REVIEW

**Comment by prokofitch** [comment]
ci:test:sf

**Comment by suilin** [comment]
Hi @CaiocSiqueira, thanks for working on the automation test, there is a conflict issue, can you rebase it and resend it? Thanks!

**Comment by prokofitch** [comment]
ci:test:sf

**Comment by suilin** [comment]
Hi @CaiocSiqueira, your steps are good for me, but seems you missed the priority property, I added it to the test. Thanks.

cc @xbrianlee

**Pull request closed without merging**
