### PR TITLE
LRQA-68951 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-68951

### CODE REVIEW

**Comment by suilin** [comment]
Hi @brookedalton, it looks good to me but could you add `Publications.viewPublicationPublished(publicationName = "Publication Name");` at the last step to assert the publication published? Thank you!

**Comment by suilin** [comment]
Hi @brookedalton, it looks good to me but could you add `Publications.viewPublicationPublished(publicationName = "Publication Name");` at the last step to assert the publication published? Thank you!

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
