### PR TITLE
LPS-173129

### PR DESCRIPTION
**Pull request by prokofitch**
https://issues.liferay.com/browse/LPS-173129

Original pull request: https://github.com/CaiocSiqueira/liferay-portal/pull/17

### CODE REVIEW

**Comment by prokofitch** [comment]
ci:test:sf

**Comment by suilin** [comment]
Hi @CaiocSiqueira, thanks for working on it, could you update your test with the following changes?
1. Update wiki page change to contian the version, due to the commit of LPS-175931, the wiki page change contains the version. 
2. Add the steps to assert wiki node change after reviewing changes.
3. Create one wiki node and wiki page is enough for the test, may I asked why you added two?

**Comment by prokofitch** [comment]
ci:test:sf

**Comment by prokofitch** [comment]
ci:test:publications:nocompile

**Comment by prokofitch** [comment]
ci:test:sf

**Comment by prokofitch** [comment]
ci:test:publications:nocompile

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
