### PR TITLE
master-qa-LRQA-57475

### PR DESCRIPTION
**Pull request by suilin**

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:search-solr:nocompile

**Comment by suilin** [comment]
ci:test:search-solr:nocompile

**Comment by suilin** [comment]
ci:test:search-solr:nocompile

**Comment by suilin** [comment]
ci:test:search-es7:nocompile

**Comment by suilin** [comment]
ci:test:search-es7:nocompile

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
